server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  datasource:
    name: test
    url: jdbc:mysql://192.168.105.4:3306/mwallet_family
    username: ipnbarcode
    password: f5!g$KpxAUb3hq53
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.example.firstspringboot.common.vo
  mapperLocations: classpath:mapper/*.xml

